# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: apt-get update
- script: apt-get upgrade
- script: apt-get install perl build-essential
- script: perl -E"say 'hello world'"
  displayName: 'Hello World via Perl'
- script: cpanm --quiet --installdeps --notest .


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
